### PR TITLE
Initial commit with bower_components added

### PR DESCRIPTION
**Pull request by priyakamesh**

### CODE REVIEW

**Comment by dmserrano** [comment]
Hey Priya. I looks like I was getting this error on page load:

```
Uncaught ReferenceError: $ is not defined
    at quiz.js:12
```

I notice that you had the three Types of robots like the requirements asked, but you will also need to have 2 unique robot models for each type. Use the same constructor function and prototype method you used to create the robot types. Here is the requirement I am talking about:

1. Define at least 2 specific robot model functions for each type.

Thanks, let me know if you have any questions.

**Comment by priyakamesh** [comment]
Hi Dom, I have created constructor function for each model. I am not getting error in quiz.js file( I think jQuery file is not loading properly for you). can you check the changes ?


Thanks Dom,   Happy New  Year.....

**Comment by dmserrano** [comment]
Happy New Year! Your code looks great. However, the display that shows the winner of the battle is only shown when one of the Robots wins. 

Also it looks like you don't have a ```jquery/dist/jquery.js``` file in the ```bower-components``` that you pushed to Github. If it is working for you, you may have the jquery file locally and it wasn't pushed up.

**Comment by dmserrano** [comment]
Awesome gifs! Your revisions look great, you are good to merge 👍

**Comment by priyakamesh** [comment]
Thanks Dom.....

**Pull request merged**
